<!-- Success Ticker Slider -->
<div
    class="bg-gradient-to-r from-green-50 to-emerald-50 rounded-xl border border-green-200 overflow-hidden shadow-sm mt-2">
    <div class="swiper successSwiper">
        <div class="swiper-wrapper">
            <!-- Slides will be dynamically generated by JavaScript -->
        </div>
    </div>
</div>

@push('scripts')
    <script>
        // Random user data generator
        const firstNames = ['John', 'Sarah', 'Mike', 'Emma', 'David', 'Lisa', 'Tom', 'Anna', 'James', 'Maria',
            'Robert', 'Jennifer', 'Michael', 'Linda', 'William', 'Patricia', 'Richard', 'Susan',
            'Joseph', 'Jessica', 'Thomas', 'Karen', 'Charles', 'Nancy', 'Daniel', 'Betty'];

        function generateRandomSlide() {
            const name = firstNames[Math.floor(Math.random() * firstNames.length)];
            const maskLength = Math.floor(Math.random() * 5) + 4; // 4-8 stars
            const maskedName = '*'.repeat(maskLength) + name.slice(-2);
            const action = Math.random() > 0.5 ? 'Withdrawal' : 'Earning';
            const amount = (Math.floor(Math.random() * 1950) + 50).toFixed(2); // 50-2000 USDT

            return `
                <div class="swiper-slide w-full">
                    <div class="flex items-center w-full gap-3 bg-white/90 backdrop-blur px-4 sm:px-6 py-2 sm:py-3 rounded-lg shadow-sm mx-2 sm:mx-4">
                        <i class="fas fa-user-circle text-green-500 text-xl sm:text-2xl"></i>
                        <div class="leading-tight">
                            <div class="font-semibold text-gray-800 text-sm sm:text-base">${maskedName}</div>
                            <div class="text-xs sm:text-sm text-green-700">
                                <i class="fas fa-check-circle"></i>
                                Successful ${action} ${amount} USDT
                            </div>
                        </div>
                    </div>
                </div>
            `;
        }

        // Initialize swiper
        function initializeSuccessSwiper() {
            const swiperWrapper = document.querySelector('.successSwiper .swiper-wrapper');

            // Generate initial slides
            for (let i = 0; i < 10; i++) {
                swiperWrapper.innerHTML += generateRandomSlide();
            }

            // Initialize Swiper
            const swiper = new Swiper('.successSwiper', {
                direction: 'vertical',
                loop: true,
                allowTouchMove: false,
                autoplay: {
                    delay: 5000,
                    disableOnInteraction: false,
                    reverseDirection: true,
                },
                speed: 800,
                effect: 'slide',
            });

            // Add new random slide every 5 seconds
            setInterval(() => {
                swiper.appendSlide(generateRandomSlide());
                if (swiper.slides.length > 20) {
                    swiper.removeSlide(0);
                }
            }, 5000);
        }

        // Initialize on page load
        document.addEventListener('DOMContentLoaded', initializeSuccessSwiper);
    </script>
@endpush