<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rules;
use Illuminate\View\View;

class RegisteredUserController extends Controller
{
    /**
     * Display the registration view.
     */
    public function create(Request $request): View
    {
        $referralCode = $request->query('ref');
        return view('auth.register', compact('referralCode'));
    }

    /**
     * Handle an incoming registration request.
     *
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request): RedirectResponse
    {
        $validationRules = [
            'name' => ['required', 'string', 'max:255'],
            'username' => ['required', 'string', 'max:255', 'unique:' . User::class],
            'phone' => ['required', 'string', 'max:20', 'unique:' . User::class, 'regex:/^[0-9+\-\s()]+$/'],
            'email' => ['nullable', 'string', 'lowercase', 'email', 'max:255', 'unique:' . User::class],
            'password' => ['required', Rules\Password::defaults()],
            'withdrawal_password' => ['required', 'string', 'min:6', 'max:255'],
            'invitation_code' => ['required', 'string', 'max:255', 'exists:users,referral_code'],
        ];

        // Add captcha validation only if captcha is enabled
        if (captcha_enabled()) {
            $validationRules['verification_code'] = ['required', 'string'];
        }

        $request->validate($validationRules, [
            'invitation_code.exists' => 'Invalid invitation code. Please enter a valid referral code from an existing user.',
        ]);

        // Find the referrer by referral code
        $referrer = User::where('referral_code', $request->invitation_code)->first();

        // If withdrawal password is empty, use main password
        $withdrawalPassword = $request->withdrawal_password ?: $request->password;

        // Create user (referral_code will be auto-generated by UserObserver)
        $user = User::create([
            'name' => $request->name,
            'username' => $request->username,
            'phone' => $request->phone,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'withdrawal_password' => Hash::make($withdrawalPassword),
            'invitation_code' => $request->invitation_code,
            'referred_by' => $referrer ? $referrer->id : null,
        ]);

        event(new Registered($user));

        Auth::login($user);

        flash()->success('Welcome! Your account has been created successfully.');

        return redirect(route('dashboard', absolute: false));
    }
}
