<?php

return [
    'supported_locales' => [
        'en' => 'English (US, UK, CA, AU)',
        'es' => 'Spanish (Spain, Mexico, Argentina)',
        'pt' => 'Portuguese (Portugal)',
        'pt-BR' => 'Portuguese (Brazil)',
        'ru' => 'Russian',
        'ko' => 'Korean',
        'ja' => 'Japanese',
        'nl' => 'Dutch (Nederland)',
        'el' => 'Greek',
        'de' => 'German',
        'ar' => 'Arabic',
        'tr' => 'Turkish',
        'zh-CN' => 'Chinese (Simplified)',
        'hi' => 'Hindi (India)',
        'ro' => 'Romanian',
    ],

    // Country code to locale mapping. If a country is not mapped, default_locale is used.
    'country_locale_map' => [
        // Arabic speaking countries
        'SA' => 'ar',
        'AE' => 'ar',
        'QA' => 'ar',
        'KW' => 'ar',
        'OM' => 'ar',
        'BH' => 'ar',
        'EG' => 'ar',
        'JO' => 'ar',
        'LB' => 'ar',
        'IQ' => 'ar',
        'SY' => 'ar',
        'YE' => 'ar',
        'PS' => 'ar',
        'DZ' => 'ar',
        'MA' => 'ar',
        'TN' => 'ar',
        'LY' => 'ar',
        'SD' => 'ar',

        // Spanish speaking countries
        'ES' => 'es',
        'MX' => 'es',
        'AR' => 'es',
        'CO' => 'es',
        'CL' => 'es',
        'PE' => 'es',
        'VE' => 'es',
        'EC' => 'es',
        'BO' => 'es',
        'PY' => 'es',
        'UY' => 'es',
        'GT' => 'es',
        'HN' => 'es',
        'SV' => 'es',
        'NI' => 'es',
        'CR' => 'es',
        'PA' => 'es',
        'DO' => 'es',

        // Portuguese
        'BR' => 'pt-BR',
        'PT' => 'pt',
        'AO' => 'pt',
        'MZ' => 'pt',

        // Other supported locales
        'RU' => 'ru',
        'KR' => 'ko',
        'JP' => 'ja',
        'NL' => 'nl',
        'GR' => 'el',
        'DE' => 'de',
        'AT' => 'de',
        'CH' => 'de',
        'TR' => 'tr',
        'CN' => 'zh-CN',
        'TW' => 'zh-CN',
        'SG' => 'zh-CN',
        'HK' => 'zh-CN',
        'IN' => 'hi',
        'RO' => 'ro',
    ],

    'default_locale' => 'en',
];
